TYPO3:
  Neos:
    modules:
      translationManagement:
        label: 'Translation Management'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'Contains a module to manage frontend translations'
        icon: 'icon-flag'
        bodyClasses: 'neos neos-module translation-browser'
        submodules:
          Translator:
            label: 'Translator'
            controller: '\Pure\Translation\Controller\Management\TranslationManagementController'
            description: 'This module is for managing translations'
            icon: 'icon-flag-alt'
            additionalResources:
              javaScripts:
                - resource://Pure.Translation/Public/JavaScripts/Main.js
              styleSheets:
                - resource://Pure.Translation/Public/Styles/Translation.css
            actions:
              index:
                label: 'Translations overview'
                title: 'Shows a list of translated labels'
Pure:
  Translation:
    #
    # A map containing path formats per package, which specify where to find
    # screenshots for each translation identifier, e.g.:
    #
    # 'Some.Package': 'resource://Some.Package/Some/Resource/Path/%s.png'
    #
    # whereas the placeholder will be replaced with the translation identifier
    #
    screenshotPaths:
      '': ''
